# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            "Mickaël Derriey's blog"
url:              https://mderriey.github.io
baseurl:          /

author:
  name:           'Mickaël Derriey'
  url:            https://twitter.com/mderriey

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mderriey/
