# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            "Mickaël Derriey's blog"
url:              https://mderriey.com

author:           'Mickaël Derriey'

twitter:
  username:       mderriey

logo:             /public/images/avatar.png

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mderriey/
