jekyll:
  image: jekyll/jekyll:latest
  container_name: blog
  command: jekyll serve --watch --incremental --force_polling
  ports:
    - 4000:4000
  volumes:
    - .:/srv/jekyll
    - ./bundle:/usr/local/bundle